=== Shyrei/RentShop/shop.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="shop">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="winterSportEquipment" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="category" type="xs:string" />
							<xs:element name="title" type="xs:string" />
							<xs:element name="price" type="xs:integer" />
							<xs:element name="sum" type="xs:integer" />
						</xs:sequence>						
					</xs:complexType>
				</xs:element>
				<xs:element name="summerSportEquipment" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="category" type="xs:string" />
							<xs:element name="title" type="xs:string" />
							<xs:element name="price" type="xs:integer" />
							<xs:element name="sum" type="xs:integer" />
						</xs:sequence>						
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Shyrei/RentShop/shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<shop xsi:noNamespaceSchemaLocation="shop.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<winterSportEquipment>
		<category>Хоккей</category>
		<title>Клюшка</title>
		<price>10</price>
		<sum>5</sum>
	</winterSportEquipment>
	<winterSportEquipment>
		<category>Хоккей</category>
		<title>Коньки</title>
		<price>20</price>
		<sum>10</sum>
	</winterSportEquipment>
	<winterSportEquipment>
		<category>Хоккей</category>
		<title>Шайбы</title>
		<price>3</price>
		<sum>20</sum>
	</winterSportEquipment>
	<winterSportEquipment>
		<category>Биатлон</category>
		<title>Костюм</title>
		<price>20</price>
		<sum>5</sum>
	</winterSportEquipment>
	<winterSportEquipment>
		<category>Биатлон</category>
		<title>Винтовка</title>
		<price>50</price>
		<sum>3</sum>
	</winterSportEquipment>
	<summerSportEquipment>
		<category>Отдых</category>
		<title>Велосипед</title>
		<price>30</price>
		<sum>10</sum>
	</summerSportEquipment>
	<summerSportEquipment>
		<category>Отдых</category>
		<title>Ролики</title>
		<price>10</price>
		<sum>2</sum>
	</summerSportEquipment>
	<summerSportEquipment>
		<category>Волейбол</category>
		<title>Мяч</title>
		<price>3</price>
		<sum>3</sum>
	</summerSportEquipment>
	<summerSportEquipment>
		<category>Волейбол</category>
		<title>Сетка</title>
		<price>7</price>
		<sum>9</sum>
	</summerSportEquipment>
	<summerSportEquipment>
		<category>Футбол</category>
		<title>Бутсы</title>
		<price>7</price>
		<sum>10</sum>
	</summerSportEquipment>
</shop>
